In [15]:
import pandas as pd

In [16]:
from sklearn.preprocessing import MinMaxScaler

In [17]:
from sklearn.model_selection import train_test_split

In [18]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
from sklearn.metrics import confusion_matrix

In [20]:
from sklearn.metrics import classification_report

In [21]:
# code out the model

In [22]:
df = pd.read_csv("baseball_1338_rows.csv", encoding = 'latin-1')

In [26]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Player 0001,3,375,1497,89,452,64,16,64,277,125,356,22,6,0.302,0
1,Player 0002,20,1560,4893,450,1189,207,20,254,665,659,490,249,82,0.243,0
2,Player 0003,17,1598,4269,363,1400,324,42,54,749,516,609,123,36,0.328,0
3,Player 0004,11,462,1791,92,440,82,24,20,278,94,401,23,3,0.246,0
4,Player 0005,11,440,1460,78,359,59,16,37,213,180,321,44,14,0.246,0

In [27]:
df = df.drop(columns = ['PLAYER', 'CS'])

In [42]:
df

,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,BA,HOF
0,3,375,1497,89,452,64,16,64,277,125,356,22,0.302,0
1,20,1560,4893,450,1189,207,20,254,665,659,490,249,0.243,0
2,17,1598,4269,363,1400,324,42,54,749,516,609,123,0.328,0
3,11,462,1791,92,440,82,24,20,278,94,401,23,0.246,0
4,11,440,1460,78,359,59,16,37,213,180,321,44,0.246,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1333,21,2856,9311,720,2277,380,123,309,1031,771,1942,493,0.245,0
1334,14,1890,6005,229,2122,351,134,289,1136,323,706,306,0.353,0
1335,25,1225,4045,162,1082,184,54,178,535,404,800,52,0.267,0
1336,16,2336,8151,587,2084,282,57,312,1054,1137,1008,132,0.256,0
1337,8,816,2734,80,740,126,33,104,472,242,321,58,0.271,0

In [49]:
X = df.iloc[:,0:13]

In [50]:
y = df.iloc[:,13]

In [51]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1333    0
1334    0
1335    0
1336    0
1337    0
Name: HOF, Length: 1338, dtype: int64

In [52]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 11, test_size = 0.2)

In [57]:
scaler = MinMaxScaler(feature_range = (0,1))

In [58]:
X_train = scaler.fit_transform(X_train)

In [60]:
X_test = scaler.fit_transform(X_test)

In [62]:
knn = KNeighborsClassifier(n_neighbors = 8)

In [63]:
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=8)

In [64]:
y_pred = knn.predict(X_test)

In [65]:
print(y_pred)

[1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0
 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0]

In [66]:
knn.score(X_test,y_test)

0.9664179104477612

In [67]:
cm = confusion_matrix(y_test, y_pred)

In [68]:
print(cm)

[[244   9]
 [  0  15]]

In [69]:
cr = classification_report(y_test, y_pred)

In [70]:
print(cr)

              precision    recall  f1-score   support

           0       1.00      0.96      0.98       253
           1       0.62      1.00      0.77        15

    accuracy                           0.97       268
   macro avg       0.81      0.98      0.88       268
weighted avg       0.98      0.97      0.97       268

In [71]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.96      0.98       253
           1       0.62      1.00      0.77        15

    accuracy                           0.97       268
   macro avg       0.81      0.98      0.88       268
weighted avg       0.98      0.97      0.97       268