In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('baseball_1338_rows.csv', encoding = 'latin-1')

In [3]:
df.head()

,PLAYER,YRS,G,AB,R,H,2B,3B,HR,RBI,BB,SO,SB,CS,BA,HOF
0,Player 0001,3,375,1497,89,452,64,16,64,277,125,356,22,6,0.302,0
1,Player 0002,20,1560,4893,450,1189,207,20,254,665,659,490,249,82,0.243,0
2,Player 0003,17,1598,4269,363,1400,324,42,54,749,516,609,123,36,0.328,0
3,Player 0004,11,462,1791,92,440,82,24,20,278,94,401,23,3,0.246,0
4,Player 0005,11,440,1460,78,359,59,16,37,213,180,321,44,14,0.246,0

In [4]:
df = df.drop(columns = ['PLAYER', 'CS'])

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X = df.iloc[:,0:13]

In [9]:
y = df.iloc[:,13]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 12, test_size = 0.2)

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
dtc = DecisionTreeClassifier()

In [15]:
dtc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'random_state': None,
 'splitter': 'best'}

In [16]:
dtc.fit(X_train, y_train)

DecisionTreeClassifier()

In [18]:
y_pred = dtc.predict(X_test)

In [34]:
from sklearn.metrics import confusion_matrix

In [35]:
print(confusion_matrix(y_test, y_pred))

[[245   4]
 [  4  15]]

In [36]:
from sklearn.metrics import classification_report

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.98      0.98       249
           1       0.79      0.79      0.79        19

    accuracy                           0.97       268
   macro avg       0.89      0.89      0.89       268
weighted avg       0.97      0.97      0.97       268

In [38]:
dtc.feature_importances_

array([0.0105148 , 0.11118766, 0.        , 0.        , 0.        ,
       0.01423545, 0.02606974, 0.81022996, 0.00625485, 0.02150754,
       0.        , 0.        , 0.        ])

In [39]:
X.columns

Index(['YRS', 'G', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'SB',
       'BA'],
      dtype='str')

In [40]:
feature = pd.DataFrame(dtc.feature_importances_,index = X.columns)

In [41]:
feature.head(15)

            0
YRS  0.010515
G    0.111188
AB   0.000000
R    0.000000
H    0.000000
2B   0.014235
3B   0.026070
HR   0.810230
RBI  0.006255
BB   0.021508
SO   0.000000
SB   0.000000
BA   0.000000

In [42]:
dtc2 = DecisionTreeClassifier(criterion = 'entropy', ccp_alpha = 0.04)

In [43]:
dtc2.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.04, criterion='entropy')

In [44]:
y_pred2 = dtc2.predict(X_test)

In [45]:
print(confusion_matrix(y_test, y_pred2))

[[234  15]
 [  0  19]]

In [46]:
dtc2.feature_importances_

array([0.       , 0.1552336, 0.       , 0.       , 0.       , 0.       ,
       0.       , 0.8447664, 0.       , 0.       , 0.       , 0.       ,
       0.       ])

In [47]:
feature2 = pd.DataFrame(dtc2.feature_importances_,index = X.columns)

In [49]:
feature2.head(15)

            0
YRS  0.000000
G    0.155234
AB   0.000000
R    0.000000
H    0.000000
2B   0.000000
3B   0.000000
HR   0.844766
RBI  0.000000
BB   0.000000
SO   0.000000
SB   0.000000
BA   0.000000