In [15]:
import pandas as pd

In [16]:
from sklearn.model_selection import train_test_split

In [17]:
# | Encoding | Common use                                     |
# | -------- | ---------------------------------------------- |
# | `utf-8`  | Modern/default choice, supports many languages |
# | `latin1` | Older Western European data; very forgiving    |
# | `cp1252` | Windows-generated Western European files       |
# | `utf-16` | Some Windows/Excel files                       |
# reason to use this encoding

In [18]:
df = pd.read_csv("medical_fixed.csv", encoding = "latin-1")

In [19]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [20]:
X = df.drop(columns = ["sex", "smoker", "region", "charges"])

In [21]:
y = df["charges"]

In [22]:
X.head()

   age     bmi  children
0   19  27.900         0
1   18  33.770         1
2   28  33.000         3
3   33  22.705         0
4   32  28.880         0

In [23]:
X.shape

(1338, 3)

In [24]:
y.shape

(1338,)

In [25]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 11, test_size = 0.2)

In [32]:
X_train.shape

(1070, 3)

In [33]:
y_train.shape

(1070,)

In [34]:
X_test.shape

(268, 3)

In [35]:
y_test.shape

(268,)

In [36]:
X_train.head()

      age     bmi  children
316    50  32.205         0
340    24  27.600         0
151    48  29.700         0
1282   18  21.660         0
557    34  34.210         0

In [38]:
X_train.describe().round(3)

            age       bmi  children
count  1070.000  1070.000  1070.000
mean     39.357    30.680     1.068
std      14.198     6.162     1.190
min      18.000    16.815     0.000
25%      26.000    26.220     0.000
50%      40.000    30.305     1.000
75%      52.000    34.800     2.000
max      64.000    53.130     5.000