In [1]:
import pandas as pd

In [2]:
d = {
    'sales': [125000, 235000, 180000, 325000, 95000, 450000, 275000, 150000, 390000, 210000, 520000, 175000],
    
    'city': ['Tampa', 'Orlando', 'Miami', 'Jacksonville', 'Tampa', 'Miami', 
             'Orlando', 'Jacksonville', 'Miami', 'Tampa', 'Orlando', 'Jacksonville'],
    
    'size': ['Small', 'Medium', 'Large', 'Large', 'Small', 'Medium', 
             'Large', 'Small', 'Medium', 'Medium', 'Large', 'Small']
}

In [3]:
df = pd.DataFrame(data = d)

In [5]:
df.head()

    sales          city    size
0  125000         Tampa   Small
1  235000       Orlando  Medium
2  180000         Miami   Large
3  325000  Jacksonville   Large
4   95000         Tampa   Small

In [7]:
df["city"].unique()

<StringArray>
['Tampa', 'Orlando', 'Miami', 'Jacksonville']
Length: 4, dtype: str

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [13]:
ohe = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False).set_output(transform = 'pandas')

In [14]:
ohetransform = ohe.fit_transform(df[["city"]])

In [15]:
ohetransform

    city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                 0.0         0.0           0.0         1.0
1                 0.0         0.0           1.0         0.0
2                 0.0         1.0           0.0         0.0
3                 1.0         0.0           0.0         0.0
4                 0.0         0.0           0.0         1.0
5                 0.0         1.0           0.0         0.0
6                 0.0         0.0           1.0         0.0
7                 1.0         0.0           0.0         0.0
8                 0.0         1.0           0.0         0.0
9                 0.0         0.0           0.0         1.0
10                0.0         0.0           1.0         0.0
11                1.0         0.0           0.0         0.0

In [16]:
 df.head()

    sales          city    size
0  125000         Tampa   Small
1  235000       Orlando  Medium
2  180000         Miami   Large
3  325000  Jacksonville   Large
4   95000         Tampa   Small

In [17]:
ohetransform.head()

   city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0                0.0         0.0           0.0         1.0
1                0.0         0.0           1.0         0.0
2                0.0         1.0           0.0         0.0
3                1.0         0.0           0.0         0.0
4                0.0         0.0           0.0         1.0

In [18]:
df = pd.concat([df, ohetransform], axis = 1).drop(columns = ["city"])

In [20]:
df.head(10)

    sales    size  city_Jacksonville  city_Miami  city_Orlando  city_Tampa
0  125000   Small                0.0         0.0           0.0         1.0
1  235000  Medium                0.0         0.0           1.0         0.0
2  180000   Large                0.0         1.0           0.0         0.0
3  325000   Large                1.0         0.0           0.0         0.0
4   95000   Small                0.0         0.0           0.0         1.0
5  450000  Medium                0.0         1.0           0.0         0.0
6  275000   Large                0.0         0.0           1.0         0.0
7  150000   Small                1.0         0.0           0.0         0.0
8  390000  Medium                0.0         1.0           0.0         0.0
9  210000  Medium                0.0         0.0           0.0         1.0