In [22]:
import pandas as pd

In [23]:
import numpy as np

In [24]:
# handling missing data in the dataset

In [25]:
miles = pd.DataFrame({'farthest_run_mi': [50,62,np.nan,100,26,13,31,50]})

In [26]:
miles

   farthest_run_mi
0             50.0
1             62.0
2              NaN
3            100.0
4             26.0
5             13.0
6             31.0
7             50.0

In [27]:
miles.isna().sum()

farthest_run_mi    1
dtype: int64

In [28]:
from sklearn.impute import SimpleImputer

In [29]:
imp_mean = SimpleImputer(strategy = 'mean') # common one for numerical

In [30]:
imp_mean.fit_transform(miles)

array([[ 50.        ],
       [ 62.        ],
       [ 47.42857143],
       [100.        ],
       [ 26.        ],
       [ 13.        ],
       [ 31.        ],
       [ 50.        ]])

In [31]:
imp_median = SimpleImputer(strategy = 'median') # common one for numerical

In [32]:
imp_median.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [33]:
imp_mode = SimpleImputer(strategy = 'most_frequent') # common one for numerical

In [34]:
imp_mode.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 50.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [35]:
imp_constant = SimpleImputer(strategy = 'constant', fill_value = 13) # one for numerical

In [36]:
imp_constant.fit_transform(miles)

array([[ 50.],
       [ 62.],
       [ 13.],
       [100.],
       [ 26.],
       [ 13.],
       [ 31.],
       [ 50.]])

In [70]:
names = pd.DataFrame({'name' : ['ryan', 'nolan', 'honus', 'wagner', np.nan, 'ruth']}) # one for categorical data

In [38]:
names

     name
0    ryan
1   nolan
2   honus
3  wagner
4     NaN
5    ruth

In [40]:
imp_constant_cat = SimpleImputer(strategy = 'constant', fill_value = 'babe')

In [44]:
imp_constant_cat.fit_transform(names)

array([['ryan'],
       ['nolan'],
       ['honus'],
       ['wagner'],
       ['babe'],
       ['ruth']], dtype=object)

In [45]:
imp_mean_marked = SimpleImputer(strategy = 'mean', add_indicator = True)

In [47]:
imp_mean_marked.fit_transform(miles)

array([[ 50.        ,   0.        ],
       [ 62.        ,   0.        ],
       [ 47.42857143,   1.        ],
       [100.        ,   0.        ],
       [ 26.        ,   0.        ],
       [ 13.        ,   0.        ],
       [ 31.        ,   0.        ],
       [ 50.        ,   0.        ]])

In [60]:
df = pd.read_csv("medical_fixed.csv")

In [61]:
df = df.drop(columns = ["sex", "smoker"])

In [62]:
df

      age     bmi  children     region      charges
0      19  27.900         0  southwest  16884.92400
1      18  33.770         1  southeast   1725.55230
2      28  33.000         3  southeast   4449.46200
3      33  22.705         0  northwest  21984.47061
4      32  28.880         0  northwest   3866.85520
...   ...     ...       ...        ...          ...
1333   50  30.970         3  northwest  10600.54830
1334   18  31.920         0  northeast   2205.98080
1335   18  36.850         0  southeast   1629.83350
1336   21  25.800         0  southwest   2007.94500
1337   61  29.070         0  northwest  29141.36030

[1338 rows x 5 columns]

In [53]:
from sklearn.compose import make_column_transformer

In [66]:
ct = make_column_transformer(
    (imp_constant_cat, ["region"]),
    (imp_mean, ['charges']),
    remainder = 'drop'
)

In [67]:
ct.set_output(transform = 'pandas')

ColumnTransformer(transformers=[('simpleimputer-1',
                                 SimpleImputer(fill_value='babe',
                                               strategy='constant'),
                                 ['region']),
                                ('simpleimputer-2', SimpleImputer(),
                                 ['charges'])])

In [68]:
df_pandas = ct.fit_transform(df)

In [69]:
df_pandas

     simpleimputer-1__region  simpleimputer-2__charges
0                  southwest               16884.92400
1                  southeast                1725.55230
2                  southeast                4449.46200
3                  northwest               21984.47061
4                  northwest                3866.85520
...                      ...                       ...
1333               northwest               10600.54830
1334               northeast                2205.98080
1335               southeast                1629.83350
1336               southwest                2007.94500
1337               northwest               29141.36030

[1338 rows x 2 columns]