In [49]:
import pandas as pd
import numpy as np

In [50]:
d1 = {
    'Social_media_followers': [1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 1500000, 1200000, 1800000, 1100000],
    'Sold_out': [1, 0, 0, 1, 0, 0, 0, 1, 0, 1]
}

In [51]:
df1 = pd.DataFrame(data = d1)

In [52]:
df1

   Social_media_followers  Sold_out
0               1000000.0         1
1                     NaN         0
2               2000000.0         0
3               1310000.0         1
4               1700000.0         0
5                     NaN         0
6               1500000.0         0
7               1200000.0         1
8               1800000.0         0
9               1100000.0         1

In [53]:
df1['Social_media_followers'].isna().sum()

np.int64(2)

In [54]:
X1 = df1[['Social_media_followers']]

In [55]:
y1 = df1[['Sold_out']]

In [56]:
from sklearn.model_selection import train_test_split

In [57]:
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size = 0.2, random_state = 13)

In [58]:
X1_train.shape

(8, 1)

In [59]:
y1_train.shape

(8, 1)

In [60]:
X1_test.shape

(2, 1)

In [61]:
from sklearn.impute import SimpleImputer

In [62]:
imputer = SimpleImputer(strategy = 'mean')

In [63]:
from sklearn.linear_model import LogisticRegression

In [42]:
lr = LogisticRegression()

In [64]:
from sklearn.pipeline import make_pipeline

In [65]:
pipe1 = make_pipeline(imputer, lr)

In [66]:
pipe1.fit(X1_train, y1_train)

/home/allen/Projects/Linux/python_scikit_learn/.venv/lib/python3.13/site-packages/sklearn/utils/validation.py:1365: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

Pipeline(steps=[('simpleimputer', SimpleImputer()),
                ('logisticregression', LogisticRegression())])

In [67]:
pipe1.score(X1_train, y1_train)

1.0

In [68]:
pipe1.score(X1_test, y1_test)

1.0

In [69]:
pipe1.named_steps.simpleimputer.statistics_

array([1471428.57142857])

In [70]:
pipe1.named_steps.logisticregression.coef_

array([[-0.00014809]])

In [71]:
# more advanced pipeline

In [72]:
d2 = {
    'Genre': ['Rock', 'Metal', 'Bluegrass', 'Rock', np.nan, 'Rock', 'Rock', np.nan, 'Rock'],
    'Social_media_followers': [1000000, np.nan, 2000000, 1310000, 1700000, np.nan, 1500000, 1200000, 1800000],
    'Sold_out': [1, 0, 0, 1, 0, 0, 1, 0, 1]
}

In [73]:
df = pd.DataFrame(data = d2)

In [74]:
df

       Genre  Social_media_followers  Sold_out
0       Rock               1000000.0         1
1      Metal                     NaN         0
2  Bluegrass               2000000.0         0
3       Rock               1310000.0         1
4        NaN               1700000.0         0
5       Rock                     NaN         0
6       Rock               1500000.0         1
7        NaN               1200000.0         0
8       Rock               1800000.0         1

In [75]:
X = df.iloc[:,0:2]

In [77]:
y = df.iloc[:,2]

In [82]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 23, test_size = 0.3)

In [83]:
X_train.shape

(6, 2)

In [84]:
X_test.shape

(3, 2)

In [85]:
num_cols = ['Social_media_followers']

In [86]:
cat_cols = ['Genre']

In [87]:
from sklearn.pipeline import Pipeline

In [88]:
from sklearn.preprocessing import StandardScaler

In [90]:
num_pipeline = Pipeline(steps = [
    ('impute', SimpleImputer(strategy = 'mean')),
    ('scale', StandardScaler())
])

In [91]:
from sklearn.preprocessing import OneHotEncoder

In [92]:
cat_pipeline = Pipeline(steps = [
    ('impute', SimpleImputer(strategy = 'most_frequent')),
    ('one-hot-encoder', OneHotEncoder(handle_unknown = 'ignore', sparse_output = False))
])

In [95]:
from sklearn.compose import ColumnTransformer

In [96]:
col_transformer = ColumnTransformer(transformers = [
    ('num_pipeline', num_pipeline, num_cols),
    ('cat_pipeline', cat_pipeline, cat_cols),
],
    remainder = 'drop',
    n_jobs = -1
)

In [97]:
from sklearn.tree import DecisionTreeClassifier

In [98]:
dtc = DecisionTreeClassifier()

In [101]:
pipefinal = make_pipeline(col_transformer, dtc)

In [102]:
pipefinal.fit(X_train, y_train)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(n_jobs=-1,
                                   transformers=[('num_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer()),
                                                                  ('scale',
                                                                   StandardScaler())]),
                                                  ['Social_media_followers']),
                                                 ('cat_pipeline',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('one-hot-encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['Genre'])])),
                ('decisiontreeclassifier', DecisionTreeClassifier())])

In [103]:
pipefinal.score(X_test, y_test)

0.3333333333333333

In [105]:
# how to save your pipeline

In [106]:
import joblib

In [107]:
joblib.dump(pipefinal, "pipe.joblib")

['pipe.joblib']

In [ ]:
pipefinal2 =