In [1]:
import pandas as pd

In [2]:
d = {
    'sales': [125000, 235000, 180000, 325000, 95000, 450000, 275000, 150000, 390000, 210000, 520000, 175000],
    
    'city': ['Tampa', 'Orlando', 'Miami', 'Jacksonville', 'Tampa', 'Miami', 
             'Orlando', 'Jacksonville', 'Miami', 'Tampa', 'Orlando', 'Jacksonville'],
    
    'size': ['Small', 'Medium', 'Large', 'Large', 'Small', 'Medium', 
             'Large', 'Small', 'Medium', 'Medium', 'Large', 'Small']
}

In [4]:
df = pd.DataFrame(data = d)

In [8]:
df.head(10)

    sales          city    size
0  125000         Tampa   Small
1  235000       Orlando  Medium
2  180000         Miami   Large
3  325000  Jacksonville   Large
4   95000         Tampa   Small
5  450000         Miami  Medium
6  275000       Orlando   Large
7  150000  Jacksonville   Small
8  390000         Miami  Medium
9  210000         Tampa  Medium

In [9]:
df["size"].unique()

<StringArray>
['Small', 'Medium', 'Large']
Length: 3, dtype: str

In [17]:
sizes = ['Small', 'Medium', 'Large']

from sklearn.preprocessing import OrdinalEncoder

In [19]:
enc = OrdinalEncoder(categories = [sizes])

In [20]:
enc.fit_transform(df[['size']])

array([[0.],
       [1.],
       [2.],
       [2.],
       [0.],
       [1.],
       [2.],
       [0.],
       [1.],
       [1.],
       [2.],
       [0.]])

In [21]:
df.head()

    sales          city    size
0  125000         Tampa   Small
1  235000       Orlando  Medium
2  180000         Miami   Large
3  325000  Jacksonville   Large
4   95000         Tampa   Small

In [22]:
df['size'] = enc.fit_transform(df[['size']])

In [23]:
df.head()

    sales          city  size
0  125000         Tampa   0.0
1  235000       Orlando   1.0
2  180000         Miami   2.0
3  325000  Jacksonville   2.0
4   95000         Tampa   0.0

In [24]:
df.head(10)

    sales          city  size
0  125000         Tampa   0.0
1  235000       Orlando   1.0
2  180000         Miami   2.0
3  325000  Jacksonville   2.0
4   95000         Tampa   0.0
5  450000         Miami   1.0
6  275000       Orlando   2.0
7  150000  Jacksonville   0.0
8  390000         Miami   1.0
9  210000         Tampa   1.0