In [36]:
import pandas as pd

In [37]:
from sklearn.model_selection import train_test_split

In [3]:
# | Encoding | Common use                                     |
# | -------- | ---------------------------------------------- |
# | `utf-8`  | Modern/default choice, supports many languages |
# | `latin1` | Older Western European data; very forgiving    |
# | `cp1252` | Windows-generated Western European files       |
# | `utf-16` | Some Windows/Excel files                       |
# reason to use this encoding

In [38]:
df = pd.read_csv("medical_fixed.csv", encoding = "latin-1")

In [39]:
df.head()

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [44]:
X = df.drop(columns = ["sex", "smoker", "region", "charges"])

In [45]:
y = df["charges"]

In [46]:
X.head()

   age     bmi  children
0   19  27.900         0
1   18  33.770         1
2   28  33.000         3
3   33  22.705         0
4   32  28.880         0

In [48]:
X.shape

(1338, 3)

In [50]:
y.shape

(1338,)

In [51]:
y.head()

0    16884.92400
1     1725.55230
2     4449.46200
3    21984.47061
4     3866.85520
Name: charges, dtype: float64

In [55]:
sp

In [57]:
X_train.shape

(1070, 3)